[package]
name = "git_detective"
version = "0.1.0"
authors = ["NickHackman <snickhackman@gmail.com>"]
edition = "2018"

[dependencies]
git2 = "0.13.5"
url = "2.1.1"
thiserror = "1.0.16"
chrono = "0.4.11"
tokei = {git = "https://github.com/NickHackman/tokei.git", branch = "annotate-files"}
